language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

cache:
  directories:
    - node_modules

#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "kotone"
  - git config user.email "1581850039@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - hexo deploy
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: https://github.com/kotone/kotone.github.io.git
